
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author harsh
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectid1 = new javax.swing.JTextField();
        selectname1 = new javax.swing.JTextField();
        selectslot1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dummy = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Course_id:");

        jLabel2.setText("Course_name");

        jLabel3.setText("Slot");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(51, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "C_id", "C_name", "slot", "Dummy id"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel4.setText("Dummy id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectid1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(selectname1)
                    .addComponent(selectslot1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(8, 8, 8))
                    .addComponent(dummy))
                .addGap(197, 197, 197)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(selectid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2))
                            .addComponent(selectname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(selectslot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dummy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(back)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int arr[]={0,0,0,0,0};
         DefaultTableModel tb1Model =(DefaultTableModel)jTable1.getModel();
        if(selectid1.getText().equals("")||selectname1.getText().equals("")||selectslot1.getText().equals("")||dummy.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter all data");
        }
        
        ResultSet rp = null;
        ResultSet rs=null;
        String id,name,slot,dummy1;
             try{
            Class.forName("com.mysql.cj.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tejes?useSSL=false","root","wartejes28") ;
         
        String query1="select *from timetable";
          PreparedStatement stm=conn.prepareStatement(query1);
             rp = stm.executeQuery();
             
             String data[]={selectid1.getText(),selectname1.getText(),selectslot1.getText(),dummy.getText()};
          /*  if(data[2].equals("A1")){
                 arr[0]=+1;
             }
            if(data[2]=="B1"){
                 arr[1]=+1;
             }
            if(data[2]=="C1"){
                 arr[2]=+1;
             }
            if(data[2]=="D1"){
                 arr[3]=+1;
             }
            if(data[2]=="E1"){
                 arr[4]=+1;
             }
            //check
            if(data[2].equals("A1")){
                 if(arr[0]!=1){
                     tb1Model.addRow(data);
             String query="insert into timetable(C_id,C_Name,slot,Dummy_id) values(?,?,?,?)";
                PreparedStatement stm1=conn.prepareStatement(query);
                stm1.setString(1, selectid1.getText());
                stm1.setString(2, selectname1.getText());
                stm1.setString(3,selectslot1.getText());
                stm1.setString(4,dummy.getText());
                stm1.executeUpdate();
            JOptionPane.showMessageDialog(this," Added Successfully");
            selectid1.setText("");
            selectname1.setText("");
            selectslot1.setText("");
            dummy.setText("");

                 }
                 else{
                         JOptionPane.showMessageDialog(this,"There is a clash with other slot");  
                 }
             }
            if(data[2]=="B1"){
                 arr[1]=+1;
             }
            if(data[2]=="C1"){
                 arr[2]=+1;
             }
            if(data[2]=="D1"){
                 arr[3]=+1;
             }
            if(data[2]=="E1"){
                 arr[4]=+1;
             }
            */
             
              tb1Model.addRow(data);
             String query="insert into timetable(C_id,C_Name,slot,Dummy_id) values(?,?,?,?)";
                PreparedStatement stm1=conn.prepareStatement(query);
                stm1.setString(1, selectid1.getText());
                stm1.setString(2, selectname1.getText());
                stm1.setString(3,selectslot1.getText());
                stm1.setString(4,dummy.getText());
                stm1.executeUpdate();
            JOptionPane.showMessageDialog(this," Added Successfully");
            selectid1.setText("");
            selectname1.setText("");
            selectslot1.setText("");
            dummy.setText("");
                   
                   
             /*  while(rp.next()){
                   String data[]={selectid1.getText(),selectname1.getText(),selectslot1.getText()};
              tb1Model.addRow(data);
                  stm=conn.prepareStatement(query1);
                 stm.setString(1,selectslot1.getText());
                   rs = stm.executeQuery(query1);
              if(rs.next()){
                  JOptionPane.showMessageDialog(this,"There is a clash with other slot");
              }*/
              /* String data1[]={selectid1.getText(),selectname1.getText(),selectslot1.getText()};
              tb1Model.addRow(data);*/
              /*else{
               String query2="insert into timetable(C_id,C_Name,slot) values(?,?,?)";
                 stm=conn.prepareStatement(query2);
                stm.setString(1, selectid1.getText());
                stm.setString(2, selectname1.getText());
                stm.setString(3,selectslot1.getText());
                stm.executeUpdate();
            JOptionPane.showMessageDialog(this,"Added Successfully");
            selectid1.setText("");
            selectname1.setText("");
            selectslot1.setText("");
                    }*/
         /*  else{
               String query1="select *from timetable where NOT IN slot=?";
                  stm=conn.prepareStatement(query1);
                 stm.setString(3,selectslot1.getText());
                       rs = stm.executeQuery(query1);
                 if(rs.next()){
                     String query="insert into timetable(C_id,C_Name,slot) values(?,?,?)";
                     stm=conn.prepareStatement(query);
                stm.setString(1, selectid1.getText());
                stm.setString(2, selectname1.getText());
                stm.setString(3,selectslot1.getText());
                stm.executeUpdate();
            JOptionPane.showMessageDialog(this,"Added Successfully");
            selectid1.setText("");
            selectname1.setText("");
            selectslot1.setText("");
                 }else{
                       JOptionPane.showMessageDialog(this,"There is a clash with other slot");
                 }
           }*/
              
                 
              }catch(Exception e){
          
             }
             
             
            
             
        
    
           
            
      //  }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        facultypage w2=new facultypage();
        w2.setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField dummy;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField selectid1;
    private javax.swing.JTextField selectname1;
    private javax.swing.JTextField selectslot1;
    // End of variables declaration//GEN-END:variables
}
